# ------------------- General Options -------------------------
description                  : AB3DMOT
seed                         : 0

# --------------- main.py
save_root                    : ./results
score_threshold              : -10000     # filter out tracklet with low confidence if necessary
hypothesis                   : 1          # >1 to allow multi-hypothesis tracking
dataset                      : KITTI      # KITTI
split                        : val        # val, test
det_method                   : pointrcnn  # name of the detector [pointrcnn, pvrcnn]
cat_list                     : ['Car', 'Pedestrian', 'Cyclist']

# --------------- model.py
ego_com                      : false
vis                          : true